services:
  database:
    image: postgres:alpine
    container_name: hedheapp-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 9920:5432
    networks:
      - app-network
  backend:
    build: .
    container_name: hedgeapp-back
    restart: always
    env_file:
      - .env
    ports:
      - 4000:3000
    depends_on:
      - database
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
